import http from "node:http";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";

const root = process.env.AUTOMATON_PAPER_TRADING_ROOT || path.join(os.homedir(), ".automaton", "paper-trading");
const port = Number(process.env.AUTOMATON_PAPER_DASHBOARD_PORT || 8787);
const host = process.env.AUTOMATON_PAPER_DASHBOARD_HOST || "127.0.0.1";
const simulator = path.resolve("scripts/paper-trading.ts");

function readJson<T>(name: string, fallback: T): T {
  try { return JSON.parse(fs.readFileSync(path.isAbsolute(name) ? name : path.join(root, name), "utf8")) as T; } catch { return fallback; }
}
function readJsonl(name: string): unknown[] {
  try { return fs.readFileSync(path.join(root, name), "utf8").split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line)); } catch { return []; }
}
function state() {
  return {
    portfolio: readJson("portfolio.json", null),
    snapshot: readJson("market-snapshot.json", null),
    trades: readJsonl("trades.jsonl").slice(-20).reverse(),
    history: readJsonl("portfolio-history.jsonl").slice(-100),
    marketCapDemo: readJson(path.resolve("config/market-cap-demo.json"), { enabled: false, source: "unavailable", marketCapsUsd: {} }),
  };
}
function run(args: string[]): Promise<{ code: number; output: string }> {
  return new Promise((resolve) => execFile(process.execPath, ["node_modules/tsx/dist/cli.mjs", simulator, ...args], { cwd: process.cwd(), timeout: 30_000 }, (error, stdout, stderr) => resolve({ code: error ? 1 : 0, output: (stderr || stdout).trim() })));
}
async function body(req: http.IncomingMessage): Promise<Record<string, unknown>> {
  let raw = "";
  for await (const part of req) { raw += part; if (raw.length > 10_000) throw new Error("Request too large"); }
  return JSON.parse(raw || "{}") as Record<string, unknown>;
}
const page = `<!doctype html><html><head><meta charset="utf-8"><title>Lamuh Paper Trading</title><style>
:root{color-scheme:dark;--bg:#09111f;--card:#111d30;--ink:#e8f0ff;--muted:#9cb0cf;--green:#38d39f;--line:#253955}*{box-sizing:border-box}body{margin:0;font:15px system-ui;background:var(--bg);color:var(--ink)}main{max-width:1200px;margin:auto;padding:28px}h1{margin:0}a{color:#73c7ff}.notice{margin:14px 0;padding:12px;border:1px solid #945b1c;background:#2c2010;color:#ffd493;border-radius:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px}.label{color:var(--muted);font-size:12px;text-transform:uppercase}.value{font-size:25px;margin-top:6px}table{width:100%;border-collapse:collapse}td,th{padding:9px;text-align:left;border-bottom:1px solid var(--line)}form{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}input,select,button{padding:10px;border-radius:7px;border:1px solid var(--line);background:#0c1728;color:var(--ink)}button{background:#176b55;cursor:pointer}button.secondary{background:#1d3556}.wide{grid-column:span 4}#message{white-space:pre-wrap;color:var(--green)}@media(max-width:650px){form{grid-template-columns:1fr 1fr}.wide{grid-column:span 2}}</style></head><body><main>
<h1>Lamuh Paper Trading</h1><p><a href="/battle">Open Market Battle view →</a></p><div class="notice"><b>SIMULATION ONLY.</b> This dashboard never connects to an exchange, wallet, account, API key, transfer, or live order system. Educational use only; not financial advice.</div>
<div id="app">Loading local simulation…</div>
<script>const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);const num=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:8});
async function api(url,opt){const r=await fetch(url,opt);const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x}
function table(rows,heads){return '<table><thead><tr>'+heads.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table>'}
function render(d){let p=d.portfolio,s=d.snapshot;if(!p){document.querySelector('#app').innerHTML='<div class=card>Portfolio files are missing. Run <code>paper-trading.cmd initialize</code> once, then refresh.</div>';return}let positions=Object.entries(p.positions||{}).map(([a,x])=>'<tr><td>'+a+'</td><td>'+num(x.quantity)+'</td><td>'+money(x.costBasisUsd)+'</td></tr>').join('')||'<tr><td colspan=3>No simulated positions</td></tr>';let prices=Object.entries(s?.pricesUsd||{}).map(([a,v])=>'<tr><td>'+a+'</td><td>'+money(v)+'</td></tr>').join('');let trades=(d.trades||[]).map(t=>'<tr><td>'+new Date(t.timestamp).toLocaleString()+'</td><td>'+t.side+' '+t.asset+'</td><td>'+money(t.notionalUsd)+'</td><td>'+t.rationale+'</td></tr>').join('')||'<tr><td colspan=4>No simulated trades yet</td></tr>';let limits=Object.entries(p.riskLimits).map(([k,v])=>'<tr><td>'+k+'</td><td>'+v+'</td></tr>').join('');let hist=(d.history||[]).slice(-10).reverse().map(h=>'<tr><td>'+new Date(h.timestamp).toLocaleString()+'</td><td>'+money(h.equityUsd)+'</td><td>'+money(h.cashUsd)+'</td></tr>').join('')||'<tr><td colspan=3>History appears after initialization / snapshots.</td></tr>';
document.querySelector('#app').innerHTML='<div class=grid><div class=card><div class=label>Virtual cash</div><div class=value>'+money(p.cashUsd)+'</div></div><div class=card><div class=label>Portfolio value</div><div class=value>'+money(p.performance.equityUsd)+'</div></div><div class=card><div class=label>Unrealized P/L</div><div class=value>'+money(p.performance.unrealizedPnlUsd)+'</div></div><div class=card><div class=label>Price refresh</div><div class=value style="font-size:15px">'+(s?new Date(s.fetchedAt).toLocaleString():'Not yet available')+'</div><button class=secondary onclick="refreshMarket()">Refresh public prices</button></div></div><div class=grid style="margin-top:14px"><section class=card>'+table(positions,['Asset','Virtual quantity','Cost basis'])+'</section><section class=card>'+table(prices,['Public price','USD'])+'</section></div><section class=card style="margin-top:14px"><h2>Record a simulated trade</h2><p>A written rationale is required. Existing paper limits are enforced by the simulator; no live action is possible.</p><form id=trade><select name=side><option value=buy>Simulated buy (USD amount)</option><option value=sell>Simulated sell (asset quantity)</option></select><select name=asset><optgroup label="Crypto"><option>BTC</option><option>ETH</option><option>SOL</option></optgroup><optgroup label="Stocks"><option>AAPL</option><option>MSFT</option><option>TSLA</option></optgroup></select><input name=amount type=number min=0 step=any placeholder="Amount" required><button>Record simulation</button><input class=wide name=rationale minlength=8 placeholder="Why is this a learning-only simulated trade?" required></form><div id=message></div></section><div class=grid style="margin-top:14px"><section class=card><h2>Recent simulated trades</h2>'+table(trades,['Time','Action','Notional','Rationale'])+'</section><section class=card><h2>Risk limits</h2>'+table(limits,['Limit','Value'])+'</section></div><section class=card style="margin-top:14px"><h2>Portfolio history</h2>'+table(hist,['Recorded','Equity','Cash'])+'</section>';
document.querySelector('#trade').onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));let m=document.querySelector('#message');m.textContent='Checking paper limits…';try{await api('/api/trade',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});m.textContent='Simulated trade recorded.';await load()}catch(err){m.textContent='Not recorded: '+err.message}}}
async function load(){render(await api('/api/state'))}async function refreshMarket(){try{await api('/api/refresh',{method:'POST'});await load()}catch(e){alert(e.message)}}load();setInterval(load,30000);</script></main></body></html>`;
const battlePage = `<!doctype html><html><head><meta charset="utf-8"><title>Market Battle — Paper Simulation</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;font:16px system-ui;color:#fff;background:radial-gradient(circle at top,#38235e,#071327 62%)}main{max-width:1080px;margin:auto;padding:26px}.warning{background:#4c2813;border:2px solid #ffaf4b;padding:14px;border-radius:12px;color:#ffe1b4}.top{display:flex;justify-content:space-between;align-items:center;gap:15px}.arena{margin:24px 0;padding:26px;border:2px solid #6377d2;border-radius:18px;background:linear-gradient(135deg,#1b1643,#102a4a);box-shadow:0 0 35px #6247aa55}.versus{font-weight:900;text-align:center;font-size:32px;color:#ffdf5a;text-shadow:2px 2px #a33157}.fighters{display:grid;grid-template-columns:1fr 80px 1fr;gap:14px;align-items:center}.fighter{padding:18px;border-radius:12px;background:#121d37;border:1px solid #7890e8}.fighter:last-child{background:#362137}.name{font-weight:800;font-size:20px}.bar{height:16px;border-radius:9px;background:#0b1020;margin:12px 0;overflow:hidden}.fill{height:100%;background:linear-gradient(90deg,#54e9c4,#b5ff7a)}.red{background:linear-gradient(90deg,#ff8d70,#fa4f93)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat{background:#111b35;border:1px solid #45588a;border-radius:10px;padding:14px}.muted{color:#c3cce5;font-size:13px}a{color:#aee8ff}table{width:100%;border-collapse:collapse;margin-top:18px;background:#111b35}td,th{padding:10px;border-bottom:1px solid #35466f;text-align:left}@media(max-width:620px){.fighters{grid-template-columns:1fr}.versus{order:2}.stats{grid-template-columns:1fr}}</style></head><body><main>
<div class="top"><h1>MARKET BATTLE</h1><a href="/">← Standard dashboard</a></div><div class="warning"><b>SIMULATION ONLY — virtual USD, virtual positions, and educational visualisation.</b> No wallet, exchange account, credentials, transfer, or live order exists here.</div>
<div id="app">Entering arena…</div><script>const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);const escape=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));async function load(){const d=await (await fetch('/api/state')).json(),p=d.portfolio,s=d.snapshot||{};if(!p){app.innerHTML='<p>Initialize the local simulator first.</p>';return}let exposure=Math.max(0,p.performance.equityUsd-p.cashUsd),limit=p.performance.equityUsd*(p.riskLimits.maxTotalExposurePct/100),pct=Math.min(100,limit?exposure/limit*100:0),rows=(d.trades||[]).slice(0,5).map(t=>'<tr><td>'+new Date(t.timestamp).toLocaleString()+'</td><td>'+escape(t.side+' '+t.asset)+'</td><td>'+money(t.notionalUsd)+'</td><td>'+escape(t.rationale)+'</td></tr>').join('')||'<tr><td colspan=4>No battle moves yet — no simulated trades recorded.</td></tr>';let cards=Object.entries(s.pricesUsd||{}).map(([a,v])=>'<div class=stat><div class=muted>'+a+' public spot price</div><b>'+money(v)+'</b></div>').join('');app.innerHTML='<section class=arena><div class=fighters><div class=fighter><div class=name>VIRTUAL CASH</div><div class=bar><div class=fill style="width:'+Math.min(100,p.cashUsd/p.startingCashUsd*100)+'%"></div></div><b>'+money(p.cashUsd)+'</b><p class=muted>Starting virtual balance: '+money(p.startingCashUsd)+'</p></div><div class=versus>VS</div><div class=fighter><div class=name>MARKET EXPOSURE</div><div class=bar><div class="fill red" style="width:'+pct+'%"></div></div><b>'+money(exposure)+' / '+money(limit)+' limit</b><p class=muted>No leverage. No shorting. Paper limit enforced.</p></div></div></section><section class=stats><div class=stat><div class=muted>Portfolio power (equity)</div><b>'+money(p.performance.equityUsd)+'</b></div><div class=stat><div class=muted>Unrealized P/L</div><b>'+money(p.performance.unrealizedPnlUsd)+'</b></div><div class=stat><div class=muted>Last public data refresh</div><b>'+(s.fetchedAt?new Date(s.fetchedAt).toLocaleString():'Unavailable')+'</b></div></section><h2>Price roster</h2><section class=stats>'+cards+'</section><h2>Recent simulated battle log</h2><table><thead><tr><th>Time</th><th>Move</th><th>Virtual amount</th><th>Learning rationale</th></tr></thead><tbody>'+rows+'</tbody></table><p class=muted>To record a rationale-required simulated trade, use the <a href="/">standard dashboard</a>. It applies the same hard paper-risk limits.</p>'}load();setInterval(load,30000)</script></main></body></html>`;
const server = http.createServer(async (req, res) => {
  const send = (status: number, value: unknown) => { res.writeHead(status, { "content-type": "application/json", "cache-control": "no-store" }); res.end(JSON.stringify(value)); };
  if (req.method === "GET" && req.url === "/") { res.writeHead(200, { "content-type": "text/html; charset=utf-8" }); res.end(page); return; }
  if (req.method === "GET" && req.url === "/battle") { res.writeHead(200, { "content-type": "text/html; charset=utf-8" }); res.end(fs.readFileSync(path.resolve("public/paper-trading-battle.html"), "utf8")); return; }
  if (req.method === "GET" && req.url === "/api/state") { send(200, state()); return; }
  if (req.method === "POST" && req.url === "/api/refresh") { const result = await run(["snapshot"]); send(result.code ? 400 : 200, result.code ? { error: result.output } : state()); return; }
  if (req.method === "POST" && req.url === "/api/trade") { try { const data = await body(req); const side = data.side === "buy" || data.side === "sell" ? data.side : null; const asset = typeof data.asset === "string" ? data.asset : ""; const amount = Number(data.amount); const rationale = typeof data.rationale === "string" ? data.rationale.trim() : ""; if (!side || !["BTC", "ETH", "SOL", "AAPL", "MSFT", "TSLA"].includes(asset) || !Number.isFinite(amount) || amount <= 0 || rationale.length < 8) throw new Error("Choose a valid simulated action, supported asset, positive amount, and rationale of at least 8 characters."); const result = await run([`simulate-${side}`, asset, String(amount), rationale]); send(result.code ? 400 : 200, result.code ? { error: result.output } : state()); } catch (error) { send(400, { error: error instanceof Error ? error.message : String(error) }); } return; }
  send(404, { error: "Not found" });
});
server.listen(port, host, () => console.log(`Paper-trading dashboard: http://${host}:${port} (paper simulation only)`));
